#!/usr/bin/env bash

set -euo pipefail

repo_root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
bin_path="$repo_root/bin/liberty2tech"
lib_path="$repo_root/SO3_L3_tt_0.7_25_nldm.lib"
tmp_dir="$(mktemp -d)"
out_path="$tmp_dir/so3.genlib"
err_path="$tmp_dir/so3.stderr"

cleanup() {
  rm -rf "$tmp_dir"
}

trap cleanup EXIT

fail() {
  printf 'test_dual_output: %s\n' "$1" >&2
  exit 1
}

"$bin_path" "$lib_path" >"$out_path" 2>"$err_path"

expected_header="# Generated by liberty2tech from $lib_path"
actual_header="$(sed -n '1p' "$out_path")"
if [[ "$actual_header" != "$expected_header" ]]; then
  fail "unexpected output header: $actual_header"
fi

if rg -q 'Parsing library|End of library|Lib Read:' "$out_path"; then
  fail "parser diagnostics leaked into generated genlib output"
fi

fa_count="$(rg -c '^GATE FA_X1_DH[[:space:]]+' "$out_path")"
ha_count="$(rg -c '^GATE HA_X1[[:space:]]+' "$out_path")"
and_count="$(rg -c '^GATE AND2_X1[[:space:]]+' "$out_path")"

if [[ "$fa_count" != "2" ]]; then
  fail "expected 2 FA_X1_DH gate records, got $fa_count"
fi

if [[ "$ha_count" != "2" ]]; then
  fail "expected 2 HA_X1 gate records, got $ha_count"
fi

if [[ "$and_count" != "1" ]]; then
  fail "expected 1 AND2_X1 gate record, got $and_count"
fi

rg -q '^GATE FA_X1_DH[[:space:]]+.*CON = ' "$out_path" || fail "missing FA_X1_DH CON output"
rg -q '^GATE FA_X1_DH[[:space:]]+.*SN = ' "$out_path" || fail "missing FA_X1_DH SN output"
rg -q '^GATE HA_X1[[:space:]]+.*CON = ' "$out_path" || fail "missing HA_X1 CON output"
rg -q '^GATE HA_X1[[:space:]]+.*SN = ' "$out_path" || fail "missing HA_X1 SN output"

printf 'dual-output regression test passed\n'
