#include <cstdio>
#include <cstdlib>
#include <cstring>

extern "C"
{
#include "../vendor/qflow/readliberty.h"
}

namespace
{

void usage( char const* argv0 )
{
  std::fprintf( stderr,
                "Usage: %s <input.lib> [-o output.genlib] [-p pattern]\n"
                "\n"
                "Converts Liberty combinational cells into a GENLIB-style library.\n"
                "This implementation reuses qflow's Liberty parser.\n",
                argv0 );
}

int compare_pins( void const* lhs, void const* rhs )
{
  auto const a = static_cast<Pin const* const*>( lhs );
  auto const b = static_cast<Pin const* const*>( rhs );
  return std::strcmp( ( *a )->name, ( *b )->name );
}

bool function_mentions_input( char const* function, Pin* const* inputs, size_t input_count )
{
  for ( size_t i = 0; i < input_count; ++i )
  {
    if ( std::strstr( function, inputs[i]->name ) != nullptr )
    {
      return true;
    }
  }
  return input_count == 0;
}

} // namespace

int main( int argc, char** argv )
{
  char const* input = nullptr;
  char const* output = nullptr;
  char* pattern = nullptr;

  for ( int i = 1; i < argc; ++i )
  {
    if ( !std::strcmp( argv[i], "-o" ) && i + 1 < argc )
    {
      output = argv[++i];
    }
    else if ( !std::strcmp( argv[i], "-p" ) && i + 1 < argc )
    {
      pattern = argv[++i];
    }
    else if ( !std::strcmp( argv[i], "-h" ) || !std::strcmp( argv[i], "--help" ) )
    {
      usage( argv[0] );
      return 0;
    }
    else if ( argv[i][0] == '-' )
    {
      std::fprintf( stderr, "Unknown option: %s\n", argv[i] );
      usage( argv[0] );
      return 1;
    }
    else if ( input == nullptr )
    {
      input = argv[i];
    }
    else
    {
      std::fprintf( stderr, "Unexpected argument: %s\n", argv[i] );
      usage( argv[0] );
      return 1;
    }
  }

  if ( input == nullptr )
  {
    usage( argv[0] );
    return 1;
  }

  FILE* out = stdout;
  if ( output != nullptr )
  {
    out = std::fopen( output, "w" );
    if ( out == nullptr )
    {
      std::perror( output );
      return 1;
    }
  }

  auto* cells = read_liberty( const_cast<char*>( input ), pattern );
  if ( cells == nullptr )
  {
    std::fprintf( stderr, "Failed to read Liberty file: %s\n", input );
    if ( out != stdout )
    {
      std::fclose( out );
    }
    return 1;
  }

  std::fprintf( out, "# Generated by liberty2tech from %s\n", input );

  for ( auto* cell = cells; cell != nullptr; cell = cell->next )
  {
    size_t input_count = 0;
    size_t output_count = 0;
    bool has_clock = false;
    for ( auto* pin = cell->pins; pin != nullptr; pin = pin->next )
    {
      if ( pin->type == PIN_CLOCK )
      {
        has_clock = true;
      }
      if ( pin->type == PIN_INPUT || pin->type == PIN_CLOCK )
      {
        ++input_count;
      }
      if ( pin->type == PIN_OUTPUT && pin->function != nullptr )
      {
        ++output_count;
      }
    }

    if ( has_clock || output_count == 0 )
    {
      continue;
    }

    auto** inputs = static_cast<Pin**>( std::calloc( input_count == 0 ? 1 : input_count, sizeof( Pin* ) ) );
    if ( inputs == nullptr )
    {
      std::perror( "calloc" );
      delete_cell_list( cells );
      if ( out != stdout )
      {
        std::fclose( out );
      }
      return 1;
    }

    auto** outputs = static_cast<Pin**>( std::calloc( output_count, sizeof( Pin* ) ) );
    if ( outputs == nullptr )
    {
      std::perror( "calloc" );
      std::free( inputs );
      delete_cell_list( cells );
      if ( out != stdout )
      {
        std::fclose( out );
      }
      return 1;
    }

    size_t idx = 0;
    size_t out_idx = 0;
    for ( auto* pin = cell->pins; pin != nullptr; pin = pin->next )
    {
      if ( pin->type == PIN_INPUT || pin->type == PIN_CLOCK )
      {
        inputs[idx++] = pin;
      }
      if ( pin->type == PIN_OUTPUT && pin->function != nullptr )
      {
        outputs[out_idx++] = pin;
      }
    }
    std::qsort( inputs, input_count, sizeof( Pin* ), compare_pins );

    double load_delay = 0.0;
    double internal_cap = 0.0;
    if ( get_values( cell, &load_delay, &internal_cap ) != 0 )
    {
      load_delay = 0.0;
      internal_cap = 0.0;
    }

    for ( size_t gate_idx = 0; gate_idx < output_count; ++gate_idx )
    {
      if ( !function_mentions_input( outputs[gate_idx]->function, inputs, input_count ) )
      {
        continue;
      }

      std::fprintf( out, "GATE %-32s %8.4f  %s;\n", cell->name, cell->area, outputs[gate_idx]->function );

      for ( size_t i = 0; i < input_count; ++i )
      {
        double cap = 0.0;
        if ( get_pincap( cell, inputs[i]->name, &cap ) != 0 || cap <= 0.0 )
        {
          cap = 1.0;
        }

        std::fprintf( out,
                      "    PIN %-16s UNKNOWN %7.4f %7.1f %8.4f %8.4f %8.4f %8.4f\n",
                      inputs[i]->name,
                      cap,
                      internal_cap > 0.0 ? internal_cap : 999.0,
                      load_delay,
                      0.0,
                      load_delay,
                      0.0 );
      }

      if ( input_count == 0 )
      {
        std::fputc( '\n', out );
      }
    }

    std::free( inputs );
    std::free( outputs );
  }

  delete_cell_list( cells );

  if ( out != stdout )
  {
    std::fclose( out );
  }

  return 0;
}
